CREATE TABLE ORAADM.INDEX_AUDIT
(
  OWNER         VARCHAR2(4000 BYTE),
  NAME_INDEX    VARCHAR2(4000 BYTE),
  OBJECT_ALIAS  VARCHAR2(4000 BYTE),
  OBJECT_TYPE   VARCHAR2(4000 BYTE),
  TIMESTAMP     DATE
)
TABLESPACE ORAADM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;


CREATE INDEX ORAADM.DATA_MONITORIA_INDEX ON ORAADM.INDEX_AUDIT
(TIMESTAMP)
LOGGING
TABLESPACE ORAADM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;
